SneakGrow:
  #指针最远催熟距离
  Center: 5
  #催熟成功后，再次催熟间隔
  Delay: 30
  #成功催熟几率
  Success_Rate: 0.35
  #催熟几次后进入冷却
  Max_Count: 5
  #玩家开关[玩家可选是否开启催熟功能]
  Player_Choice: true
#保底模式[不得同时开启两个模式]
  LuckMode:
    #是否开启保底催熟[含催熟失败与成功，失败会增加计时次数]
    enabled: false
    #催熟几次会触发保底
    GrowNecessary_Count: 7
#常规模式[不得同时开启两个模式]
  CommonMode:
    #定次催熟开关
    #到达次数必定催熟成功，含催熟失败与成功，失败不会增加冷却次数
    enabled: true
    #定时催熟次数
    GrowCommon_Count: 5
    #是否开启连续击催熟
    Shift_Enabled: true
    #玩家必须在多少秒内再次点击?
    Shift_Time: 10






