SneakGrow:
  #催熟面朝玩家的距离
  Center: 5
  #催熟成功后使用间隔
  Delay: 30
  #成功催熟几率
  Success_Rate: 0.35
  #一回合能催几次
  Max_Count: 5
  #是否开启必然性催熟
  Is_GrowNecessary: true
  #必然催熟次数
  GrowNecessary_Count: 7


